### ISSUE TITLE
Uncomment BPDM API call

### ISSUE THREAD

**Issue by dilipdhankecha2530** [eclipse-tractusx/vas-country-risk-backend#11]

**Comment by fabiodmota** [comment]
Can you be more specific ?  are you referring to our external call service in java?

**Comment by dilipdhankecha2530** [comment]
Yes.
Please refere [here](https://github.com/eclipse-tractusx/vas-country-risk-backend/blob/main/src/main/java/org/eclipse/tractusx/valueaddedservice/service/logic/ExternalBusinessPartnersLogicService.java#L72)

Currently, we launch the static data response from here. Uncomment the invoke service in externalBpdm service class.

**Comment by fabiodmota** [comment]
so this done on
https://github.com/catenax-ng/tx-vas-country-risk-backend/commit/5ca94633e35d4c0afc04e84557af77b0674556f4

**Comment by dilipdhankecha2530** [comment]
Maybe no.
Here you remove the invoke service call and load dummy json directly from the resource file. Before removing this line invoke service having call of BPDM service.
What's the use of that service and why still not call the actual BPDM API instand of loading dummy json?

**Comment by fabiodmota** [comment]
The service exists because it will be called directly once the other side is ready. 
I don't want to remove all the logic just to do it again later. 
As soon as the other side has the data ready for me to receive, I will simply replace the line with dummy data with the commented line that I removed. That's why the logic remains the same, the calls remain the same, with only the exchange of one line for another. It doesn't make sense to me to change what is already programmed for the use cases we have.

**Comment by dilipdhankecha2530** [comment]
One more and last question,
When we really expect the fully working functionality?

**Comment by fabiodmota** [comment]
We currently don't have any specific dates set. As of today, any new functionality in this app is taking a backseat, as the external service is being developed with top priority.
